### ==============================================================================
### ERP AGRO PERUVIAN FOODS S.A.C. - MÓDULO PRODUCCIÓN & RECETAS BOM
### Responsable: Isaí Armuto (Tríada UPeU: ADS | BD2 | LP2)
### Puerto Base: http://localhost:8080/api/v1/produccion
### ==============================================================================

@baseUrl = http://localhost:8080/api/v1/produccion

### 1. Listar todas las órdenes de producción
GET {{baseUrl}}/ordenes
Accept: application/json

### 2. Consultar orden de producción por ID
GET {{baseUrl}}/ordenes/1
Accept: application/json

### 3. Crear una nueva orden de producción con lista de materiales (BOM)
POST {{baseUrl}}/ordenes
Content-Type: application/json
Accept: application/json

{
  "productoId": 1,
  "nombreProducto": "Quinua Blanca Real Orgánica 1kg",
  "cantidadProgramada": 350,
  "observaciones": "Lote especial de exportación - Envasado al vacío",
  "insumos": [
    {
      "insumoId": 9,
      "nombreInsumo": "Bolsa Bilaminada al Vacío 1kg",
      "cantidadRequerida": 350.0,
      "cantidadConsumida": 350.0,
      "unidadMedida": "UNIDADES"
    },
    {
      "insumoId": 8,
      "nombreInsumo": "Caja de Cartón Corrugado 10kg Export",
      "cantidadRequerida": 35.0,
      "cantidadConsumida": 35.0,
      "unidadMedida": "UNIDADES"
    }
  ]
}

### 4. Iniciar la orden de producción en planta
PUT {{baseUrl}}/ordenes/3/iniciar
Accept: application/json

### 5. Completar orden, dar de alta al stock en catálogo y generar lote con vencimiento (FEFO)
PUT {{baseUrl}}/ordenes/3/completar
Content-Type: application/json
Accept: application/json

{
  "cantidadProducida": 350,
  "fechaVencimiento": "2027-09-20"
}

### 6. Consultar lotes disponibles de un producto ordenados por vencimiento más próximo (Criterio FEFO)
GET {{baseUrl}}/lotes/producto/1/fefo
Accept: application/json

### 7. Generar reporte agregado de eficiencia de producción
GET {{baseUrl}}/resumen
Accept: application/json

### 8. Cancelar una orden de producción planificada
POST {{baseUrl}}/ordenes/2/cancelar
Accept: application/json
