server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bomerp_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS BOM_CATALOGO\;CREATE SCHEMA IF NOT EXISTS BOM_CAJA\;CREATE SCHEMA IF NOT EXISTS BOM_COMPRAS\;CREATE SCHEMA IF NOT EXISTS BOM_PRODUCCION\;CREATE SCHEMA IF NOT EXISTS BOM_VENTAS
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    pe.edu.upeu.bomerp: INFO
    org.springframework.jdbc: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
