-- DATOS SEMILLA ERP AGRO PERUVIAN FOODS
-- 1. CATEGORIAS
INSERT INTO BOM_CATALOGO.CATEGORIAS (ID, NOMBRE, DESCRIPCION) VALUES (1, 'Granos Andinos', 'Granos originarios de alto valor nutricional: quinua, kiwicha, canihua');
INSERT INTO BOM_CATALOGO.CATEGORIAS (ID, NOMBRE, DESCRIPCION) VALUES (2, 'Superfoods y Frutas', 'Frutas frescas y derivados para exportacion: palta hass, arandano, lucuma');
INSERT INTO BOM_CATALOGO.CATEGORIAS (ID, NOMBRE, DESCRIPCION) VALUES (3, 'Insumos Agricolas', 'Fertilizantes organicos, abonos certificados y correctores de suelo');
INSERT INTO BOM_CATALOGO.CATEGORIAS (ID, NOMBRE, DESCRIPCION) VALUES (4, 'Materiales de Empaque', 'Cajas de carton exportacion, bolsas bilaminadas y precintos de seguridad');

-- 2. PRODUCTOS
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (1, 'Quinua Blanca Real Organica 1kg', 14.50, 850, 1);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (2, 'Quinua Roja Seleccionada 1kg', 16.00, 420, 1);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (3, 'Palta Hass Calibre 16 Exportacion', 8.50, 1200, 2);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (4, 'Arandano Fresco Biloxi Clamshell 125g', 6.20, 900, 2);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (5, 'Harina de Lucuma Pura 250g', 18.00, 310, 2);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (6, 'Mango Kent Fresco Caja 4kg', 28.00, 150, 2);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (7, 'Cacao Nativo Chuncho en Grano 1kg', 24.00, 500, 1);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (8, 'Caja de Carton Corrugado 10kg Export', 4.20, 2500, 4);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (9, 'Bolsa Bilaminada al Vacio 1kg', 0.80, 5000, 4);
INSERT INTO BOM_CATALOGO.PRODUCTOS (ID, NOMBRE, PRECIO, STOCK, ID_CATEGORIA) VALUES (10, 'Compost Organico Certificado Saco 50kg', 35.00, 200, 3);

-- 3. PROVEEDORES
INSERT INTO BOM_COMPRAS.PROVEEDORES (ID, RUC, RAZON_SOCIAL, TELEFONO, EMAIL, DIRECCION) VALUES (1, '20601234567', 'Cooperativa Agraria Productores de Ayacucho', '966123456', 'ventas@coopayacucho.pe', 'Av. Independencia 450, Huamanga, Ayacucho');
INSERT INTO BOM_COMPRAS.PROVEEDORES (ID, RUC, RAZON_SOCIAL, TELEFONO, EMAIL, DIRECCION) VALUES (2, '20558974123', 'Empaques y Cajas Industriales del Peru SAC', '014258963', 'contacto@empaquesperu.com', 'Av. Argentina 2850, Callao, Lima');
INSERT INTO BOM_COMPRAS.PROVEEDORES (ID, RUC, RAZON_SOCIAL, TELEFONO, EMAIL, DIRECCION) VALUES (3, '20489632145', 'BioFertilizantes Ecologicos del Mantaro SRL', '964852147', 'biofertil@mantaro.pe', 'Carretera Central Km 118, Concepcion, Junin');

-- 4. SESIONES Y MOVIMIENTOS CAJA
INSERT INTO BOM_CAJA.SESIONES_CAJA (ID, CAJERO_NOMBRE, FECHA_APERTURA, FECHA_CIERRE, MONTO_APERTURA, MONTO_CIERRE, SALDO_TEORICO, SALDO_REAL, DIFERENCIA, ESTADO, OBSERVACIONES) VALUES (1, 'Brandon Ccalla', TIMESTAMP '2026-09-13 08:00:00', NULL, 500.00, NULL, 730.00, NULL, NULL, 'ABIERTA', 'Sesion de caja activa turno manana');
INSERT INTO BOM_CAJA.MOVIMIENTOS_CAJA (ID, ID_SESION_CAJA, TIPO, MONTO, CONCEPTO, METODO_PAGO, REFERENCIA, FECHA) VALUES (1, 1, 'INGRESO', 250.00, 'Venta mostrador ticket TKT-001', 'EFECTIVO', 'TKT-001', TIMESTAMP '2026-09-13 08:30:00');
INSERT INTO BOM_CAJA.MOVIMIENTOS_CAJA (ID, ID_SESION_CAJA, TIPO, MONTO, CONCEPTO, METODO_PAGO, REFERENCIA, FECHA) VALUES (2, 1, 'EGRESO', 20.00, 'Caja chica cinta de embalaje', 'EFECTIVO', 'REC-0045', TIMESTAMP '2026-09-13 09:15:00');

-- 5. ORDENES DE PRODUCCION, CONSUMO Y LOTES
INSERT INTO BOM_PRODUCCION.ORDENES_PRODUCCION (ID, CODIGO_ORDEN, ID_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD_PROGRAMADA, CANTIDAD_PRODUCIDA, FECHA_INICIO, FECHA_FIN, ESTADO, OBSERVACIONES) VALUES (1, 'OP-20260910-001', 1, 'Quinua Blanca Real Organica 1kg', 500, 500, TIMESTAMP '2026-09-10 07:00:00', TIMESTAMP '2026-09-11 16:00:00', 'COMPLETADA', 'Proceso de seleccion y envasado al vacio');
INSERT INTO BOM_PRODUCCION.ORDENES_PRODUCCION (ID, CODIGO_ORDEN, ID_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD_PROGRAMADA, CANTIDAD_PRODUCIDA, FECHA_INICIO, FECHA_FIN, ESTADO, OBSERVACIONES) VALUES (2, 'OP-20260913-002', 3, 'Palta Hass Calibre 16 Exportacion', 800, NULL, TIMESTAMP '2026-09-13 06:30:00', NULL, 'EN_PROCESO', 'Lavado y empaque');
INSERT INTO BOM_PRODUCCION.DETALLES_CONSUMO_INSUMO (ID, ID_ORDEN_PRODUCCION, ID_INSUMO, NOMBRE_INSUMO, CANTIDAD_REQUERIDA, CANTIDAD_CONSUMIDA, UNIDAD_MEDIDA) VALUES (1, 1, 9, 'Bolsa Bilaminada al Vacio 1kg', 500.000, 500.000, 'UNIDADES');
INSERT INTO BOM_PRODUCCION.DETALLES_CONSUMO_INSUMO (ID, ID_ORDEN_PRODUCCION, ID_INSUMO, NOMBRE_INSUMO, CANTIDAD_REQUERIDA, CANTIDAD_CONSUMIDA, UNIDAD_MEDIDA) VALUES (2, 2, 8, 'Caja de Carton Corrugado 10kg Export', 80.000, 40.000, 'UNIDADES');
INSERT INTO BOM_PRODUCCION.LOTES_PRODUCTO (ID, CODIGO_LOTE, ID_PRODUCTO, NOMBRE_PRODUCTO, STOCK_DISPONIBLE, FECHA_PRODUCCION, FECHA_VENCIMIENTO) VALUES (1, 'LOT-20260911-01', 1, 'Quinua Blanca Real Organica 1kg', 500, DATE '2026-09-11', DATE '2027-09-11');
INSERT INTO BOM_PRODUCCION.LOTES_PRODUCTO (ID, CODIGO_LOTE, ID_PRODUCTO, NOMBRE_PRODUCTO, STOCK_DISPONIBLE, FECHA_PRODUCCION, FECHA_VENCIMIENTO) VALUES (2, 'LOT-20260901-02', 4, 'Arandano Fresco Biloxi Clamshell 125g', 300, DATE '2026-09-01', DATE '2026-10-15');

-- 6. COMPRAS Y DETALLES
INSERT INTO BOM_COMPRAS.COMPRAS (ID, NUMERO_COMPROBANTE, ID_PROVEEDOR, FECHA_EMISION, ESTADO, SUBTOTAL, IGV, TOTAL, SALDO_PENDIENTE) VALUES (1, 'F001-0004521', 2, DATE '2026-09-08', 'PAGADA', 847.46, 152.54, 1000.00, 0.00);
INSERT INTO BOM_COMPRAS.COMPRAS (ID, NUMERO_COMPROBANTE, ID_PROVEEDOR, FECHA_EMISION, ESTADO, SUBTOTAL, IGV, TOTAL, SALDO_PENDIENTE) VALUES (2, 'F002-0008910', 1, DATE '2026-09-12', 'REGISTRADA', 2542.37, 457.63, 3000.00, 1500.00);
INSERT INTO BOM_COMPRAS.DETALLE_COMPRAS (ID, ID_COMPRA, ID_INSUMO, NOMBRE_INSUMO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL) VALUES (1, 1, 9, 'Bolsa Bilaminada al Vacio 1kg', 1250.000, 0.80, 1000.00);
INSERT INTO BOM_COMPRAS.DETALLE_COMPRAS (ID, ID_COMPRA, ID_INSUMO, NOMBRE_INSUMO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL) VALUES (2, 2, 1, 'Quinua en Grano Bruto', 300.000, 10.00, 3000.00);

-- 7. VENTAS Y DETALLES
INSERT INTO BOM_VENTAS.VENTAS (ID, NUMERO_TICKET, FECHA, ESTADO, METODO_PAGO, SUBTOTAL, IGV, TOTAL, CLIENTE_NOMBRE) VALUES (1, 'TKT-20260913-001', TIMESTAMP '2026-09-13 08:30:00', 'REGISTRADA', 'EFECTIVO', 211.86, 38.14, 250.00, 'Distribuidora BioAndes SAC');
INSERT INTO BOM_VENTAS.DETALLE_VENTAS (ID, ID_VENTA, ID_PRODUCTO, ID_LOTE, NOMBRE_PRODUCTO, PRECIO_UNITARIO, CANTIDAD, SUBTOTAL) VALUES (1, 1, 1, 1, 'Quinua Blanca Real Organica 1kg', 14.50, 10, 145.00);
INSERT INTO BOM_VENTAS.DETALLE_VENTAS (ID, ID_VENTA, ID_PRODUCTO, ID_LOTE, NOMBRE_PRODUCTO, PRECIO_UNITARIO, CANTIDAD, SUBTOTAL) VALUES (2, 1, 4, 2, 'Arandano Fresco Biloxi Clamshell 125g', 6.20, 17, 105.40);
